### PR TITLE
Mainly student post function

### PR DESCRIPTION
**Pull request by cheng-wang2002**

### CODE REVIEW

**Comment by hs38Song** [comment]
I think it is good

**Comment by hs38Song** [comment]
It shows the conlfict is too complicated

**Review by EduHive-Platform — APPROVED** [review]

**Review by EduHive-Platform — APPROVED** [review]

**Review by EduHive-Platform — APPROVED** [review]

**Review by EduHive-Platform — APPROVED** [review]

**Review by EduHive-Platform — APPROVED** [review]

**Review by EduHive-Platform — APPROVED** [review]

**Review by EduHive-Platform — APPROVED** [review]

**Comment by EduHive-Platform** [comment]
conflicts all merged, see develop branch

**Comment by hs38Song** [comment]
nb

**Pull request closed without merging**
